### ISSUE TITLE
ImportError: cannot import name 'Snap'

### ISSUE THREAD

**Issue by ghost** [Rob--/SnapWrap#16]
I am using the example and I am getting this error on line 1.

**Comment by grumo35** [comment]
> I am using the example and I am getting this error on line 1.

Got the same issue dunno what's happening

**Comment by sansjack** [comment]
> > I am using the example and I am getting this error on line 1.
> 
> Got the same issue dunno what's happening

its kinda obvious that the api doesnt work anymore, snapchat has grown so much. They dont want people using these sorta of apis as they could be used maliciously. The only way is to find some open end point but there is not many

**Comment by Rob--** [comment]
Yep, this library is years outdated. The Snapchat API is extremely hard to access, I can imagine the few people who are able to access the API have insiders working with them.
