### ISSUE TITLE
I need help installing SnapWrap

### ISSUE THREAD

**Issue by kneelesh48** [Rob--/SnapWrap#18]
I did the following process in a linux terminal to install it

```
git clone https://github.com/Rob--/SnapWrap
cd SnapWrap
python setup.py install
python
import snapchat
```
And I get the following error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'snapchat'
```

What am I doing wrong?
Should the folder be in $PATH?

Please help!

**Comment by kneelesh48** [comment]
I figured this Module is outdated and has outdated dependencies. It need to be updated in order to make it work. Snapchat API has probably also changed in the last 6 years.

**Comment by Rob--** [comment]
Yeah, this wrapper is outdated. Should probably archive the repo!
