### ISSUE TITLE
pls help very important

### ISSUE THREAD

**Issue by Leclowndu93150** [Rob--/SnapWrap#20]
Traceback (most recent call last):
  File "C:\Users\karim\PycharmProjects\snapbot\main.py", line 1, in <module>
    from snapchat import Snapchat
ModuleNotFoundError: No module named 'snapchat'

**Comment by couldbejake** [comment]
I'm pretty sure this project is deprecated (meaning it's no longer supported), but it's possible you installed with a different version of python.

ie you installed with python 2.7 and tried running with python 3.6.

you can use 'python3' in the command line to install or run with python 3.
