### ISSUE TITLE
Error in the example

### ISSUE THREAD

**Issue by atestu** [Rob--/SnapWrap#6]
I'm getting this error when trying to run the example.

```
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    from SnapWrap import Snapchat
  File "SnapWrap/SnapWrap/__init__.py", line 2, in <module>
    from snapchat import Snapchat
  File "SnapWrap/SnapWrap/snapchat.py", line 2, in <module>
    from SnapWrap import Client, Snap
ImportError: cannot import name Client
```

(I'm running python 2.7.6)

**Comment by Rob--** [comment]
This is a simple fix, sorry for the trouble. You could try cloning the library and try and solve it yourself. I'll investigate when I get home from school.

**Comment by atestu** [comment]
Thanks, no worries. I'm very new at Python so I have no idea how to do that sorry :-/

**Comment by Rob--** [comment]
It should work - try downloading the repo as a `.zip` file and then running `python setup.py install`. If you're still having trouble then post a comment, if it's fixed also either tell me so I can close the issue or close it yourself.

May I ask why you're using Python 2.7.6? I haven't tested it on this version, the lowest I've tested is 2.7.9.

**Comment by Rob--** [comment]
I presume you've sorted everything out.

**Comment by atestu** [comment]
2.7.6 is the one that came with my Mac. I downloaded the zip and now it's working, thanks a lot and sorry for not responding earlier!
