### ISSUE TITLE
SnapWrap failing (?)

### ISSUE THREAD

**Issue by jkaberg** [Rob--/SnapWrap#8]
When running my script, I see the following

> python snapbot2.py
> 
> > /usr/local/lib/python2.7/dist-packages/SnapWrap-0.2->py2.7.egg/SnapWrap/Client/**init**.py(113)login()
> > -> result = self._request('loq/login', {
> > (Pdb)

But it dosn't repost incoming snaps to it's story, my script is: http://pastebin.com/Ktjx5g4e

Any ideas?

**Comment by danwatco** [comment]
Hi, we accidentally left in a python debugger in the program, if you download the latest version, it should be fix, you will need to rebuild the library first though. Sorry for the problems

**Comment by jkaberg** [comment]
Thanks again, working now! :-)
